name: Deploy Backend to Render

on:
  push:
    branches: [main]
    paths:
      - 'server/**'
      - 'requirements.txt'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Render
        uses: render-oss/deploy-to-render@v1
        with:
          # Your Render service name
          service_name: harry-potter-qna-backend
          # The directory containing your FastAPI app
          directory: server
          # The command to start your FastAPI app
          start_command: "uvicorn app:app --host 0.0.0.0 --port 10000"
          # Your Render API token (create at https://dashboard.render.com/account/api-keys)
          render_token: ${{ secrets.RENDER_TOKEN }}
          # Your Render account ID (find in your dashboard URL)
          render_account_id: ${{ secrets.RENDER_ACCOUNT_ID }}
